### ISSUE TITLE
运行漫巡后不识别【交互】奖励点

### ISSUE THREAD

**Issue by TangMeow77** [CrashTechnologyOfficer/autohelper_baijinghuilang#11]
从最新的1.5.7版本，到之前的1.4.7版本
我挑着下了四五个版本，开循环凹漫巡技能后，走到  [交互]奖励点   这个位置，就开始弹出【运行异常，未知弹窗无法处理】
每一个版本都是！！
这到底是挂机还是要手动啊？？

![b82e5603-1bad-405f-a423-6ed4c921f8aa](https://github.com/user-attachments/assets/07d5d896-6f72-4b87-9677-db86b35dff39)

脚本软件版本：
1.5.7.7
1.5.7.6
1.5.7.5
1.5.7.2
1.5.4.7

windows操作系统:
 Windows 10

模拟器版本:
 [如使用模拟器]MuMu模拟器12 V3.9.5（3129）

上传日志:
将脚本安装目录的logs,screenshots,config,click_screenshots打包上传附件

**Comment by TangMeow77** [comment]
压缩文件195mb发不上来，发百度网盘了。
链接：https://pan.baidu.com/s/1Sz6jGdfYTRhyBeQ5MPfCfw 
提取码：jxwh 
--来自百度网盘超级会员V7的分享

**Comment by TangMeow77** [comment]
后续补充：只要行进过程中遇到任何一个【[交互点]奖励】这挂机软件都会停下来，导致它无法识别，有的【[前进]继续前进】也不识别，尤其是最后一关战斗之前有个【[前进]继续前进】，它又停下来了。

**Comment by ok-oldking** [comment]
adb截图

**Comment by TangMeow77** [comment]
我没懂adb是什么……
以及我才发现昨天好像只打包了截图，忘了其他文件，一起重新打了个包传网盘了。【click_screenshots】这个文件没有，所以就把所有文件夹都打包了……你自己看看要用到啥（挠头）

链接: https://pan.baidu.com/s/1vWU2RdV4i1CrYQ3CtvfkCQ 提取码: cug3 
--来自百度网盘超级会员v7的分享

**Comment by ok-oldking** [comment]
软件首页有个选项是adb截图

**Comment by TangMeow77** [comment]
ok啦！终于能挂机了呜呜呜
感谢！

**Comment by TangMeow77** [comment]
![082e0d0f-3462-41fa-a102-93d6463b0480](https://github.com/user-attachments/assets/8198ed1d-a904-4f2b-9e51-ee20c1606e09)
新的截图方式出现了新的问题!!
orz
一到这种界面：【左边记忆强化，右边烙痕唤醒】，就又不动弹啦！
新的bug也不弹窗，就是单纯的不往下进行了。
