### ISSUE TITLE
[BUG]用了adb截图以后新bug出现了……

### ISSUE THREAD

**Issue by TangMeow77** [CrashTechnologyOfficer/autohelper_baijinghuilang#12]
![082e0d0f-3462-41fa-a102-93d6463b0480](https://github.com/user-attachments/assets/9096f9da-99a1-406d-a8a1-44ab7aaaa97d)

新bug出现了，走到这种【一边是记忆强化，一边是烙痕唤醒】选项的时候，就停止不动啦。
没有弹窗，也不进行下一步，就没反应了。
手动选择一边以后还能继续，但是再次遇到就有停滞不前了。

**Comment by ok-oldking** [comment]
等八月一看看官方的自动漫巡
