### ISSUE TITLE
连接状态异常

### ISSUE THREAD

**Issue by hesperiso** [CrashTechnologyOfficer/autohelper_baijinghuilang#2]
![QQ图片20240530161139](https://github.com/ok-oldking/ok-baijing/assets/29257721/4d000eaa-3459-4dd4-8620-207c77befbf9)
不论能不能连上模拟器和PC端程序都显示断开

**Comment by ok-oldking** [comment]
下个最新版本， 模拟器窗口这里点选择窗口，要跟模拟器的窗口名字一样
