### ISSUE TITLE
请问PC端正确的打开方式是什么

### ISSUE THREAD

**Issue by kppok6666** [CrashTechnologyOfficer/autohelper_baijinghuilang#3]
两个压缩包我都下载来试过了，都没有办法正常运行出来，一个弹出运行错误的提示，另一个窗口闪过就没有了
![{8QLMK(}I}06C64JXBT@F G](https://github.com/ok-oldking/ok-baijing/assets/171288311/202bff25-83c1-4d66-bb95-00c53c9a0d8b)
![A3CU(} FM%SSAKE65`D9ITB](https://github.com/ok-oldking/ok-baijing/assets/171288311/8e60c527-cf64-40be-b368-ae0f2f18077f)

**Comment by ok-oldking** [comment]
报错信息可以全发出来吗

**Comment by ok-oldking** [comment]
像是windows 10 比较低的版本，如果是win10的话，试试更新最新win10系统. 今天可能再搞个支持低版本windows的

**Comment by kppok6666** [comment]
> 像是windows 10 比较低的版本，如果是win10的话，试试更新最新win10系统.今天可能再搞个支持低版本windows的

对！！！我的系统自从买了之后再也没有更新过了，呜呜呜，我不是很想更新系统
![%N@Q$OB30ETAW`%_`ED2P F](https://github.com/ok-oldking/ok-baijing/assets/171288311/8084ad31-2c9c-4f32-a385-c75a1aa667a0)

**Comment by ok-oldking** [comment]
等晚点我更新个版本 试试

**Comment by ok-oldking** [comment]
1.1.43版本已修复，支持低版本windows。你可以试试

**Comment by kppok6666** [comment]
有点心碎，成功打开了，换了几次窗口大小之后总算是能动了，但是巡游到战斗关卡那里，直接胜利那里就不动了，再然后就没有然后了
![QQ图片20240531200745](https://github.com/ok-oldking/ok-baijing/assets/171288311/6c55fc62-3c32-4c09-89c8-f4ce4e2a4a0a)

**Comment by ok-oldking** [comment]
打包发下logs和screenshots文件夹

**Comment by kppok6666** [comment]
![SJMS66}3( YV~IT1{54A~UA](https://github.com/ok-oldking/ok-baijing/assets/171288311/ae862a1c-88be-461e-8770-7573defd7a83)
![NK6)AOGNWHO6%M3DKMMX@RK](https://github.com/ok-oldking/ok-baijing/assets/171288311/0c5811f3-87f1-496b-970a-68b7d5c1c77c)
[logs.zip](https://github.com/user-attachments/files/15513830/logs.zip)
另一个压缩包放不上来了，它提示我太大了，只能截图给你看

**Comment by ok-oldking** [comment]
优化了下，试试新版本

**Comment by kppok6666** [comment]
谢谢大佬！！！总算跑完了一次战乱，耗时比较久，中间还是会停下来报错，依旧是上面的那个报错的截图，重新再点继续还是能跑，我换了空想地图，动得好像比战乱快一点，不过停下来报错的次数也多，感觉一趟跑完起码一个小时起步，但是我一把就凹出了大力出奇迹！！！感恩大佬！！！

**Comment by ok-oldking** [comment]
你用的是debug版还是release，debug会慢。一个小时有点太久了。你cpu什么配置，windows什么版本，跑的时候游戏分辨率试试改成720p试试。好像是windows10低级版本，这个PC版截图会很慢很耗性能，你试试用模拟器装个安卓版，或者电脑连接安卓机打开开发者模式试试

**Comment by kppok6666** [comment]
电脑比较老了，买了之后就没有更新过了，不过我换了720P的确实快了很多，跑了空想的路线差不多半个小时左右一把跑完，也没有再出现报错停止的情况了，十分感谢耐心的解答和优化~
![R N9TZ3P 9CQ}TGXM 0RZJ](https://github.com/ok-oldking/ok-baijing/assets/171288311/4c6ff1b7-fed2-45b6-a382-7ca7c307d0e1)
