### ISSUE TITLE
虽然不算是bug，但是能改改让每点一次的速度快一点吗？虽然循环刷挺好，但是官方自带的自动比这个快很多啊[BUG]

### ISSUE THREAD

**Issue by ZhaoPan6788** [CrashTechnologyOfficer/autohelper_baijinghuilang#4]
描述错误:
[请清晰简洁地描述错误是什么]

复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。

脚本软件版本：
[如]1.1.1

windows操作系统:
 [例如] Windows 11 Pro 23H2 22631.3593

模拟器版本:
 [如使用模拟器]MuMu模拟器12 V3.8.25 (2927)

上传日志:
将脚本安装目录的logs,screenshots,config,click_screenshots打包上传附件

**Comment by ok-oldking** [comment]
使用窗口截图 分辨率改成720p
不能跟官方比，这个不是挂，是图像识别+模拟点击

**Comment by 67762961** [comment]
官方直接调取数据的，肯定比识图快。不过话说可以考虑做个快捷键启停，或者log小窗啥的，有时候手动关弹窗就会出点儿小问题。
