### ISSUE TITLE
[TIPS] 自动更新后原先配置被覆盖

### ISSUE THREAD

**Issue by 67762961** [CrashTechnologyOfficer/autohelper_baijinghuilang#9]
（并非BUG 但是算是些小问题？）
描述:
打开时自动更新了最新的v1.4.0，准备试试新漫巡的时候发现原来的漫巡凹技能配置0覆盖成了小樱子福利院的配置，但是收菜的配置却还是原来的没有变。似乎是更新的时候覆盖了默认配置文件？或者是调试新漫巡的文件？主要是有几个自定义路径的配置，覆盖完都有点儿记不得是哪几个了。

脚本软件版本：
v1.4.1

操作系统:
Windows 10 专业版 22H2

模拟器版本:
PC桌面端

**Comment by ok-oldking** [comment]
正常之前漫巡不支持跑了,现在只能跑福利院, 配置不兼容, 所以重置了
